# Generated by Django 3.0.8 on 2022-05-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='profile',
            new_name='author',
        ),
    ]
