# Generated by Django 3.0.8 on 2022-05-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20220515_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
